### ISSUE TITLE
Cldr Backend `data_dir` on compile time

### ISSUE THREAD

**Issue by maennchen** [elixir-cldr/cldr_numbers#21]
When compiling, the `data_dir` is being written into the module.

https://github.com/elixir-cldr/cldr/blob/v2.23.2/lib/cldr/config/config.ex#L2518

When using releases, that is not working if the paths change on the runtime machine.

Would it be possible to leave the `data_dir` empty in the compiled config and recompute the data dir when it is needed?

**Comment by kipcole9** [comment]
Really appreciate you digging into this!  As of commit [7ccda04](https://github.com/elixir-cldr/cldr_numbers/commit/7ccda0433781fa21c53f4d6f90d50460704f6f90), the underlying performance issue is fixed and a new function to retrieve defined RBNF rule names for a locale is added.  

I have published [ex_cldr_numbers version 2.23.0-rc.1](https://hex.pm/packages/ex_cldr_numbers/2.23.0-rc.1) that includes the fix and the new functions.  See the docs for [Cldr.Rbnf.rule_names_for_locale/1](https://hexdocs.pm/ex_cldr_numbers/2.23.0-rc.1/Cldr.Rbnf.html#rule_names_for_locale/1) for the new function.

The changelog entry reads:

### Enhancements

* Adds `Cldr.Rbnf.rule_names_for_locale/1` to return the available RBNF rule names for a given locale.

### Bug Fixes

* Fixes performance issue when calling `Cldr.Number.to_string/3` with an arbitrary RBNF rule name. Previously these formats would mistakenly read the raw json file for a locale incurring a significant performance penaly. Performance is now 100x faster as expected. Thanks to @maennchen for the bug report. Closes #21.

This issue included two parts; the idea of dynamic location of locale data files and being able to retrieve RBNF rule names for a given locale. This update resolves the second part. I am now less convinced about needing to make locale data file location be dynamic. However if this remains something you need, please open another issue and we can work it through.

As always, thanks for the collaboration and support.
