### ISSUE TITLE
Handle Decimal NaN and Infinity

### ISSUE THREAD

**Issue by sh41** [elixir-cldr/cldr_numbers#26]
Thanks for the great library. Is it possible to handle the `NaN` and `Infinity` types of `Decimal`s? 

I can see that there are symbols configured for them, but I cannot see how to use them:
```
iex(1)> Alpha.Cldr.Number.Symbol.number_symbols_for("en", "latn")
{:ok,
 %Cldr.Number.Symbol{
   decimal: ".",
   exponential: "E",
   group: ",",
   infinity: "∞",
   list: ";",
   minus_sign: "-",
   nan: "NaN",
   per_mille: "‰",
   percent_sign: "%",
   plus_sign: "+",
   superscripting_exponent: "×",
   time_separator: ":"
 }}
```
I wrote a test to try to explore creating a PR to add the functionality: 
```elixir
  test "decimal NaN and Infinity" do
    assert {:ok, "NaN"} = Cldr.Number.to_string(Decimal.new("NaN"))
    assert {:ok, "-NaN"} = Cldr.Number.to_string(Decimal.new("-NaN"))
    assert {:ok, "∞"} = Cldr.Number.to_string(Decimal.new("Infinity"))
    assert {:ok, "-∞"} = Cldr.Number.to_string(Decimal.new("-Infinity"))
  end
  ```
which has shown that I'm doing something wrong somewhere: 
```
  1) test decimal rbnf for decimal NaN and Infinity (Rbnf.Test)
     test/number/rbnf_test.exs:105
     ** (FunctionClauseError) no function clause matching in Integer.digits/2

     The following arguments were given to Integer.digits/2:
     
         # 1
         :NaN
     
         # 2
         10
     
     Attempted function clauses (showing 1 out of 1):
     
         def digits(integer, base) when is_integer(integer) and is_integer(base) and base >= 2
     
     code: assert {:ok, "NaN"} = Cldr.Number.to_string(Decimal.new("NaN"))
     stacktrace:
       (elixir 1.13.1) lib/integer.ex:190: Integer.digits/2
       (cldr_utils 2.17.1) lib/cldr/utils/digits.ex:387: Cldr.Digits.to_digits/1
       (cldr_utils 2.17.1) lib/cldr/utils/digits.ex:375: Cldr.Digits.to_digits/1
       (cldr_utils 2.17.1) lib/cldr/utils/digits.ex:318: Cldr.Digits.to_tuple/1
       (ex_cldr_numbers 2.25.1) lib/cldr/number/formatter/decimal_formatter.ex:255: Cldr.Number.Formatter.Decimal.output_to_tuple/4
       (ex_cldr_numbers 2.25.1) lib/cldr/number/backend/decimal_formatter.ex:1: TestBackend.Cldr.Number.Formatter.Decimal.to_string/3
       (ex_cldr_numbers 2.25.1) lib/cldr/number.ex:393: Cldr.Number.to_string/3
       test/number/rbnf_test.exs:106: (test)
```

Happy to work on a PR for this, but I could benefit from some pointers on where it would be appropriate to change the code. On inspection I can see that the `coef` property of a `Decimal` will be set to either `:NaN` or `:inf` as appropriate. The `sign` property is used as it is for any other number. 

My first thought is to add a pattern match here: https://github.com/elixir-cldr/cldr_numbers/blob/master/lib/cldr/number/formatter/decimal_formatter.ex#L79 which deals with this specific case, but I wanted to check that this would be appropriate and that it is desired as a PR. 

Thanks again for the library!

**Comment by kipcole9** [comment]
@sh41 Thanks very much for the report and for making an effort to try out a PR.

In the interests of runtime performance there is a lot going on at compile time to optimise the formatting pipeline at runtime so it definitely not a straight forward piece of code to understand.

`NaN` and `Inf` need to be special-cased which is easy enough and I'll get that done over the next couple of days. Hope thats soon enough to meet your needs?

**Comment by sh41** [comment]
Thanks @kipcole9, that would be fantastic.

**Comment by kipcole9** [comment]
I've pushed [a2b9991](https://github.com/elixir-cldr/cldr_numbers/commit/a2b9991e5f0c72e06df79e6b1d8e192fd84739d2) that I believe fixes this issue.  Before I publish to hex would you consider trying it out?  

Should just need `{ex_cldr_numbers, github: "elixir-cldr/cldr_numbers"}` in your `mix.exs`.

Of course please reopen if for some reason it is no formatting as expected.

**Comment by kipcole9** [comment]
As a side note, formatting `Inf` and `NaN` needs to be applicable to any formatting string. Formats can have arbitrary text in them too. Which ultimately meant that detecting `Inf` and `NaN` had to be applied to every formatting pipeline, not just as one general case.  Here's one example from the tests:
```elixir
assert {:ok, "∞ and beyond"} = Cldr.Number.to_string(Decimal.new("Inf"), format: "# and beyond")
```

**Comment by sh41** [comment]
Hi @kipcole9, I've tested and it all looks as expected. Thank you very much for doing this.
