### ISSUE TITLE
Optional digital_tokens Dependency

### ISSUE THREAD

**Issue by maennchen** [elixir-cldr/cldr_numbers#28]
Thanks for the addition of cryptocurrencies, that is a great addition!

I wondered if the digital token dependency could be marked as optional and the code paths conditionally compiled.

The reason for that is that I think cryptocurrencies are not a classic requirement for users of a number formatting library and the compilation time could be improved if it was not there.

What do you think? If you agree, I would be happy to provide a PR.

**Comment by kipcole9** [comment]
Thanks for the feedback!

I went round in circles a few times on this. I ended up with it as a fixed configuration for the following reasons:
1. There are quite a few points of insertion that would make conditional processing messy and some level of maintenance overhead
2. I didn't want to have documentation referring to functionality that is only conditionally present. It makes discovery and developer experience a bit less than optimal
3. Both `ex_cldr_numbers` and `ex_money` can use `digital_token` and I though having that lib optional would make it more complex to manage (this is probably not really true on reflection).

I completely accept your view that its slowing down compilation. If that's the primary issue then I can most definitely pre-parse the registry content and just load an ETF file which is very quick and should bring compilation back to what it was without the library.  

If I can recover the compilation performance would that largely address your concern?

**Comment by maennchen** [comment]
@kipcole9 My main concern is the compilation speed.

While I think it would be preferable to have it optional and document the optionality of the feature nicely, I see that it brings complexity to building and also using the library when digital currencies are used.

That said, I think you can weigh the pros/cons better than I, and I trust your decision on this.

When you wrote ETF file, did you mean ETS?

**Comment by kipcole9** [comment]
ETF -> Erlang Term Format file, still statically compiled into the code but all prepared. Its very quick.

**Comment by maennchen** [comment]
@kipcole9 Ah, makes sense :)

**Comment by maennchen** [comment]
@kipcole9 In our CIs I see it around 6-7 seconds. So it is not very bad. I just thought that it is something that can be avoided if not needed.

**Comment by kipcole9** [comment]
I have published [digital_token version 0.4.0](https://hex.pm/packages/digital_token/0.4.0) that significantly improves compile time for `digital_token` by parsing and formatting the data at download time, rather than compile time.

Let me know if this brings performance back to previsous levels?

**Comment by maennchen** [comment]
@kipcole9 I see around a 40% improvement :)
