### ISSUE TITLE
Wrong spelling for french in locales such as Belgium or Switzerland

### ISSUE THREAD

**Issue by bortzmeyer** [elixir-cldr/cldr_numbers#40]
Numbers are not spelled in the same way in France or in french-speaking Belgium. For instance, 70 is "soixante-dix" in France but "septante" in Belgium.

```
# Fine:
iex(10)> MyApp.Cldr.Number.to_string 70, format: :spellout, locale: "fr-FR"
{:ok, "soixante-dix"}

# Assume France by default:
iex(9)> MyApp.Cldr.Number.to_string 70, format: :spellout, locale: "fr"   
{:ok, "soixante-dix"}

# Wrong:
iex(11)> MyApp.Cldr.Number.to_string 70, format: :spellout, locale: "fr-BE"
{:ok, "soixante-dix"}
iex(12)> MyApp.Cldr.Number.to_string 70, format: :spellout, locale: "fr-CH"
{:ok, "soixante-dix"}
```

**Comment by kipcole9** [comment]
I think this is a case where you haven't configured `fr-BE` and `fr-CH` in your CLDR backend module.  When I configure those locales I see:
```elixir
iex> MyApp.Cldr.Number.to_string 70, format: :spellout, locale: "fr"
{:ok, "soixante-dix"}
iex> MyApp.Cldr.Number.to_string 70, format: :spellout, locale: "fr-BE"
{:ok, "septante"}
iex> MyApp.Cldr.Number.to_string 70, format: :spellout, locale: "fr-CH"
{:ok, "septante"}
```
If you have only `fr` configured, attempting to use `fr-BE` will fall back to `fr` and hence the results you are seeing.

Can you confirm your CLDR backend configuration contains all three locales?  If you are ok to add it to this issue I can also test on my side.

**Comment by bortzmeyer** [comment]
I confirm. I thought that ` fr` would include all locales starting with fr.  I tested and you're right,n it works if  compile with locale `:fr_BE`.

**Comment by kipcole9** [comment]
I take a conservative view when configuring locales because of the size of the locale data.  The fallback chain of locales is configured automatically so when you configure `fr-CH`, `fr` will automatically be configured. This is done because some data that is common between both locales is only in `fr`.

If you want to be more expansive you can use wildcards. So you could configure `fr-*` to get all of the related French language locales. Just note that there are 45 of them so maybe not such a recommended idea in most cases:
```elixir
[:"fr-BE", :"fr-BF", :"fr-BI", :"fr-BJ", :"fr-BL", :"fr-CA", :"fr-CD", :"fr-CF",
 :"fr-CG", :"fr-CH", :"fr-CI", :"fr-CM", :"fr-DJ", :"fr-DZ", :"fr-GA", :"fr-GF",
 :"fr-GN", :"fr-GP", :"fr-GQ", :"fr-HT", :"fr-KM", :"fr-LU", :"fr-MA", :"fr-MC",
 :"fr-MF", :"fr-MG", :"fr-ML", :"fr-MQ", :"fr-MR", :"fr-MU", :"fr-NC", :"fr-NE",
 :"fr-PF", :"fr-PM", :"fr-RE", :"fr-RW", :"fr-SC", :"fr-SN", :"fr-SY", :"fr-TD",
 :"fr-TG", :"fr-TN", :"fr-VU", :"fr-WF", :"fr-YT"]
```
