### ISSUE TITLE
Cldr.UnknownFormatError when specifying number system

### ISSUE THREAD

**Issue by petrus-jvrensburg** [elixir-cldr/cldr_numbers#42]
Not sure if this is a bug or just a number system that's not supported. But for Tamil:

```
> Cldr.Number.System.number_systems_for!("ta", DemoApp.Backend)
%{default: :latn, native: :tamldec, traditional: :taml}
```

Both `:default` and `:native` works, but when trying `:traditional` I get:
```
> Cldr.Number.to_string!(12345, locale: "ta", number_system: :traditional)
** (Cldr.UnknownFormatError) The locale :ta with number system :taml does not define a format :standard
    (ex_cldr_numbers 2.31.3) lib/cldr/number.ex:485: Cldr.Number.to_string!/3
    /Users/petrus/code/i18n-livebooks/04-numbers.livemd#cell:imvv6j4golpgcmkyjsxhrg7l5s2yrbc7:1: (file)
```

**Comment by kipcole9** [comment]
This one is operating as intended.  The `:taml` traditional number system does not have decimal digits and therefore only supports rules based number formats.  As a result is defines no `:standard` format. There isn't really a way to decide which, if any, of the rules (as in RBNF) would make sense as a `:standard` implementation, hence the error return. 

There is some ability to introspect this:
```elixir
iex> MyApp.Cldr.Number.System.number_systems_for :ta
{:ok, %{default: :latn, native: :tamldec, traditional: :taml}}

# No digits in the :taml number system 
iex> Cldr.Number.System.number_system_digits(:taml)
{:error,
 {Cldr.UnknownNumberSystemError,
  "The number system :taml is not known or does not have digits"}}

# There are digits for the :tamldec number system
iex> Cldr.Number.System.number_system_digits(:tamldec)
{:ok, "௦௧௨௩௪௫௬௭௮௯"}
```

**Comment by petrus-jvrensburg** [comment]
Okay thanks.

Would it make sene to just leave `:taml` out of the list, since it's not supported?

Or alternatively, could there be an internal check and then a more descriptive error, like maybe `Cldr.NumberSystemNotSupportedError`?

**Comment by kipcole9** [comment]
:taml is supported, but only with RBNF formats.I agree the error message can be clearer so I’ll definitely revise that and see how I can make the devx experience better.(On a plane on phone so sorry for the brevity and formatting)Sent from my iPhoneOn 13 Aug 2023, at 17:35, Petrus Janse van Rensburg ***@***.***> wrote:﻿
Okay thanks.
Would it make sene to just leave :taml out of the list, since it's not supported?
Or alternatively, could there be an internal check and then a more descriptive error, like maybe Cldr.NumberSystemNotSupportedError?

**Comment by kipcole9** [comment]
I've asked a question on the Unicode Slack about what the best practise for handling this:

> When formatting a number with a number system that is algorithmic (like taml number system that is the traditional number system for locale ta), what does CLDR (or ICU) use for a "default format" - if at all. In my current implementation I return an error if no "standard" format can be resolved but perhaps there is a better practise?  Should I use the RBNF NumberingSystemRules with the tamil ruleset?  How would I algorithmically determine that I should use that ruleset? (Similar for Hebrew, Cyrillic, ....).  I can't see any data that links the number system (like taml to a NumberingSystemRule like tamil.  Any guidance appreciated!

There is an RBNF rule called `tamil` but I don't know if that's intended as a default for for number system `taml`. Similar issue for Hebrew and other languages where the number system is algorithmic, not digits based.

Will keep tracking and update here when there's new information.

**Comment by petrus-jvrensburg** [comment]
Thanks
