### ISSUE TITLE
Typespec in Cldr.Number does not match typespec in Cldr.Number.Backend.Number

### ISSUE THREAD

**Issue by Munksgaard** [elixir-cldr/cldr_numbers#44]
As mentioned in https://github.com/elixir-cldr/cldr_currencies/issues/11, I'm having issues in my projects that use Cldr after adding `:extra_return` to my dialyzer options.

One of the errors I'm getting is the following, which indicates an error in the typespec of `to_string!/2`:

```
lib/leaf_web/cldr.ex:1:extra_range
The type specification has too many types for the function.

Function:
LeafWeb.Cldr.Number.to_string!/2

Extra type:
atom()

Success typing:
binary()
```

And indeed, [this typespec](https://github.com/elixir-cldr/cldr_numbers/blob/5e0d054bdb2d7a07f266bfa744c55349c2edde12/lib/cldr/number.ex#L473-L478) does not match [this typespec](https://github.com/elixir-cldr/cldr_numbers/blob/5e0d054bdb2d7a07f266bfa744c55349c2edde12/lib/cldr/number/backend/number.ex#L418-L419) which I'm guessing it should.

As in the cldr_currencies issue, I can submit a PR to fix this myself, but I'm not sure how best to avoid such mistakes in the future.

**Comment by kipcole9** [comment]
A PR is definitely welcome. And I noted in the other issue, I'm adding function calls in a "test" module to ensure they get exercised and therefore dialyzer will check them. I think that will improve test outcomes quite a lot.
