### ISSUE TITLE
Dialyzer warnings - Elixir 1.16

### ISSUE THREAD

**Issue by Ali-Doggaz** [elixir-cldr/cldr_numbers#47]
Hello, I am using Elixir 1.16 + the following ex_cldr dependencies:
<img width="422" alt="image" src="https://github.com/elixir-cldr/cldr_numbers/assets/62618334/961f2f08-e5e4-4650-b65e-a60f8405287d">

I checked cldr_number's changelogs, and saw that in V2.32.3 the compiler warnings were fixed.
<img width="897" alt="image" src="https://github.com/elixir-cldr/cldr_numbers/assets/62618334/2255304c-60a5-4425-a52d-bd456f794a6e">

Yet, running `mix dialyzer --format github` generates the following warnings:
```
Total errors: 10, Skipped: 1, Unnecessary Skips: 0
done in 0m8.93s
::warning file=lib/redacted/cldr.ex,line=1,title=contract_supertype::Type specification for with_locale is a supertype of the success typing.
::warning file=lib/redacted/cldr.ex,line=1,title=contract_supertype::Type specification for known_currency_codes is a supertype of the success typing.
::warning file=lib/redacted/cldr.ex,line=1,title=contract_supertype::Type specification for to_string is a supertype of the success typing.
::warning file=lib/redacted/cldr.ex,line=1,title=contract_supertype::Type specification for to_string! is a supertype of the success typing.
::warning file=lib/redacted/cldr.ex,line=1,title=contract_supertype::Type specification for plural_rules is a supertype of the success typing.
::warning file=lib/redacted/cldr.ex,line=1,title=contract_supertype::Type specification for all_formats_for! is a supertype of the success typing.
::warning file=lib/redacted/cldr.ex,line=1,title=contract_supertype::Type specification for default_grouping_for! is a supertype of the success typing.
::warning file=lib/redacted/cldr.ex,line=1,title=contract_supertype::Type specification for minimum_grouping_digits_for! is a supertype of the success typing.
::warning file=lib/redacted/cldr.ex,line=1,title=contract_supertype::Type specification for number_systems_like is a supertype of the success typing.
done (warnings were emitted)
Halting VM with exit status 2
```

**Comment by kipcole9** [comment]
I'll take a look. Can you please:

1. Paste text, not images. Its a lot work for me to have to retype your configuration and its more error prone than copy/paste
2. Can you please post you ex_cldr backend module configuration so I can be assured of using the same configuration as you.

**Comment by Ali-Doggaz** [comment]
Oh yes, absolutely. And thanks for the quick answer, appreciate it :)

mix.exs (relevant part):
```elixir      
      {:ex_cldr, "~> 2.37.5"},
      {:ex_cldr_dates_times, "~> 2.16.0"},
      {:ex_cldr_numbers, "~> 2.32.4"}
```

Backend module: 
```elixir      
      defmodule Fiasco.Cldr do
  @doc """
  Define a backend module that will host our
  Cldr configuration and public API.

  Most function calls in Cldr will be calls
  to functions on this module.
  """

  use Cldr, otp_app: :redacted
end

```

and here is config.exs:

```elixir
config :fiasco, FiascoWeb.Gettext, default_locale: "en", default_browser_language: "de", locales: ~w(de en)
config :fiasco, Fiasco.Cldr,
  default_locale: "de",
  locales: ["de", "en"],
  gettext: Fiasco.Gettext,
  providers: [Cldr.Number, Cldr.DateTime]
```

Here are the warnings too in text format if that can help:
```
Total errors: 10, Skipped: 1, Unnecessary Skips: 0
done in 0m8.93s
::warning file=lib/fiasco/cldr.ex,line=1,title=contract_supertype::Type specification for with_locale is a supertype of the success typing.
::warning file=lib/fiasco/cldr.ex,line=1,title=contract_supertype::Type specification for known_currency_codes is a supertype of the success typing.
::warning file=lib/fiasco/cldr.ex,line=1,title=contract_supertype::Type specification for to_string is a supertype of the success typing.
::warning file=lib/fiasco/cldr.ex,line=1,title=contract_supertype::Type specification for to_string! is a supertype of the success typing.
::warning file=lib/fiasco/cldr.ex,line=1,title=contract_supertype::Type specification for plural_rules is a supertype of the success typing.
::warning file=lib/fiasco/cldr.ex,line=1,title=contract_supertype::Type specification for all_formats_for! is a supertype of the success typing.
::warning file=lib/fiasco/cldr.ex,line=1,title=contract_supertype::Type specification for default_grouping_for! is a supertype of the success typing.
::warning file=lib/fiasco/cldr.ex,line=1,title=contract_supertype::Type specification for minimum_grouping_digits_for! is a supertype of the success typing.
::warning file=lib/fiasco/cldr.ex,line=1,title=contract_supertype::Type specification for number_systems_like is a supertype of the success typing.
done (warnings were emitted)
Halting VM with exit status 2
```

**Comment by kipcole9** [comment]
Ah, I only see those errors when I configure `dialyzer: [flags: [:underspecs]]` in `mix.exs`. I'll have to dig further into this.  I'm not sure these are warnings I'm going to focus on removing - dialyzer is tricky enough to manage as it is. But I'll take a look over the weekend and see if they can be resolved without creating more issues.

**Comment by kipcole9** [comment]
I am working on this in the background on the CLDR44 branch (of this library and others). I expect I can resolve all the warnings, but it is significant work and I don't expect to have it complete for a few weeks given other priorities.

**Comment by Ali-Doggaz** [comment]
Thank you for your efforts @kipcole9 !

**Comment by kipcole9** [comment]
These super type warnings are now fixed in the cldr44 branches of `ex_cldr`, `ex_cldr_currencies`, `ex_cldr_numbers` and `ex_cldr_calendars`.  I'll keep working through these as I build out the CLDR 44-based release. But there is quite a lot of work still to do in `ex_cldr_units` so I think it's still a month away to a full release. (and thanks for the encouragement).

**Comment by kipcole9** [comment]
I've fixed this in the CLDR45 branch so I'm closing now since the CLDR data is frozen and we're a week away from release (on the 17th April).
