### ISSUE TITLE
Parsing of spelled out numbers?

### ISSUE THREAD

**Issue by mayel** [elixir-cldr/cldr_numbers#48]
We're still having lots of fun with the experiment in #46 and wondered if it'd be possible to parse spelled out numbers (eg. `forty two`) into integers (`42`). Doesn't seem that https://hexdocs.pm/ex_cldr_numbers/Cldr.Number.Parser.html#parse/2 supports it... how hard would it be to add?

**Comment by kipcole9** [comment]
I think for a single locale, like English, it might not be too hard. You'd need to separate out the grammar from the syntax (white space, commas, `and`). I think it would be a fun exercise to do in [nimble_parsec](https://hex.pm/packages/nimble_parsec).

I don't have the capacity at the moment to add this, and I'm not sure I'd consider it in scope (although I'm persuadable.  

If you and you son want to have some fun with parser combinators I'm more than happy to provide some mentorship/support.

**Comment by kipcole9** [comment]
Closing since I'm hoping you've written a lovely parser. Or you've worked out I can't help you. Feel free to reopen if required.

**Comment by mayel** [comment]
Thanks @kipcole9 :) haven't tried yet but may return to this at some point...
