### ISSUE TITLE
Compiling in isolation to build Nix packages requires prod.exs and other things

### ISSUE THREAD

**Issue by camelpunch** [elixir-cldr/cldr_numbers#49]
I noticed this discrepancy from most libraries when installing `cldr` via Nix. Nix's `buildMix` function [sets `MIX_ENV=prod`](https://github.com/NixOS/nixpkgs/blob/ab3fc0538d2012d5da74fb6a28c78f2c37831998/pkgs/development/beam-modules/build-mix.nix#L19), which works fine for most dependencies, but not this or `cldr_currencies`.

Is there a reason for not including a `prod.exs`? We can work around this in the Nix builders if so.

**Comment by kipcole9** [comment]
I have no idea how that file disappeared!  Thanks for the report. I've published [ex_cldr_currencies version 2.16.1](https://hex.pm/packages/ex_cldr_currencies/2.16.1) with the following changelog:

### Bug Fixes

* Add `config/prod.exs` so `MIX_ENV=prod` compilation succeeds. Thanks to @camelpunch for the report. Closes #49.

Sorry for the inconvenience.

**Comment by camelpunch** [comment]
Thank you!

**Comment by kipcole9** [comment]
I was surprised when this came up - but thats because when used as a dependency, library configuration is completely ignored. Your use case is therefore a little unusual - but totally reasonable. There are some other `ex_cldr` libs that don't have a `config/prod.exs` too - I'll add them as and when there is a maintenance release or you raise another issue.

**Comment by camelpunch** [comment]
Thanks! I've come across another one during today's localisation efforts: [ex_cldr_plugs](https://github.com/elixir-cldr/cldr_plugs).

I might send you some PRs to make the libs easier to compile in sandboxed environments like Nix. I've got it working with a hack. In short, the ability to override [cldr_data_dir](https://github.com/elixir-cldr/cldr/blob/ccb1a6e6d7ec98b8c45e9fec6c13f71240ad685e/lib/cldr/config/config.ex#L58) at compile time would make things a lot more straightforward.

**Comment by kipcole9** [comment]
I'm still confused as to your compilation environment. When used as a dependency, a libraries configuration is completely ignored - only the configuration of the host app is considered.  

Can you explain more about why overriding `@cldr_data_dir` would help? The required data files for `ex_cldr` (other than locale json files whose location can be configured per ex_cldr backend module) are an intrinsic part of the library and storing them outside the library seems an unusual request.

**Comment by camelpunch** [comment]
There are at least two ways of compiling dependencies in a Nix-based Elixir app:

1. Fixed-output, where the whole app's dependencies are downloaded and compiled, and a hash is taken of the result.
2. Every Mix library is wrapped in a Nix package.

(1) might work fine, but it has the downside of needing everything to be recompiled whenever any dependency changes. (2) can take advantage of Nix caching, so CI runs can be pretty fast when dependencies don't change much.

I'm interested in getting (2) to work. With standard tools, this means that each dependency of my app is compiled in isolation, in a sandboxed environment. Dependent packages are available, but aren't necessarily in the same state they'd be if they'd been compiled in a more 'global' environment.

In particular, the path generated by `:code.priv_dir/1` doesn't point to anything when compiling `ex_cldr_currencies` in isolation. So to hack around this, I've linked the dir containing the JSON files from `ex_cldr` to the path at `@cldr_data_dir`. I can put this hack into Nix dependency translators, but it'd be a little less of a hack if that path could be set.

I've got some time tomorrow so should be able to prepare something that demonstrates this with a minimal repro case.

**Comment by kipcole9** [comment]
Ah, now I understand. Sorry for being slow on the uptake. 

> path generated by :code.priv_dir/1 doesn't point to anything when compiling ex_cldr_currencies in isolation

I'll look into this. I don;'t think `ex_cldr_currencies` should be using the knowledge of `:code.priv_dir(:ex_cldr)` but I've not been in that code for a while so I'll have to review it. It *should* be using functions in `Cldr.Config` to access data but perhaps I didn't hold myself to that contract at some point.

I will keep adding `config/prod.exs` to the libs as I update them. If you have others in scope (like `ex_cldr_plugs`) I can prioritise those.

**Comment by camelpunch** [comment]
Here's the repro case. If you have `nix` installed with flakes enabled, you can do:

```shell
$ nix build -L github:camelpunch/locale_repro
ex_cldr_currencies> Running phase: unpackPhase
ex_cldr_currencies> unpacking source archive /nix/store/8if23zqvsx3qs63z49fr2lrbqvjc2s1p-hex-source-ex_cldr_currencies-2.16.1
ex_cldr_currencies> source root is hex-source-ex_cldr_currencies-2.16.1
ex_cldr_currencies> Running phase: patchPhase
ex_cldr_currencies> Running phase: updateAutotoolsGnuConfigScriptsPhase
ex_cldr_currencies> Running phase: configurePhase
ex_cldr_currencies> Running phase: buildPhase
ex_cldr_currencies> Compiling 11 files (.ex)
ex_cldr_currencies> == Compilation error in file lib/cldr/currency.ex ==
ex_cldr_currencies> ** (File.Error) could not read file "/build/hex-source-ex_cldr-2.38.0/_build/prod/lib/ex_cldr/priv/cldr/territory_currencies.json": no such file or directory
ex_cldr_currencies>     (elixir 1.16.2) lib/file.ex:384: File.read!/1
ex_cldr_currencies>     (ex_cldr 2.38.0) lib/cldr/config/config.ex:1459: Cldr.Config.territory_currency_data/0
ex_cldr_currencies>     lib/cldr/currency.ex:681: (module)
error: builder for '/nix/store/s8xcb7jh5jsvkwmmllrj1v3rqfxdgx86-ex_cldr_currencies-2.16.1.drv' failed with exit code 1;
       last 14 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/8if23zqvsx3qs63z49fr2lrbqvjc2s1p-hex-source-ex_cldr_currencies-2.16.1
       > source root is hex-source-ex_cldr_currencies-2.16.1
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > Running phase: buildPhase
       > Compiling 11 files (.ex)
       >
       > == Compilation error in file lib/cldr/currency.ex ==
       > ** (File.Error) could not read file "/build/hex-source-ex_cldr-2.38.0/_build/prod/lib/ex_cldr/priv/cldr/territory_currencies.json": no such file or directory
       >     (elixir 1.16.2) lib/file.ex:384: File.read!/1
       >     (ex_cldr 2.38.0) lib/cldr/config/config.ex:1459: Cldr.Config.territory_currency_data/0
       >     lib/cldr/currency.ex:681: (module)
       For full logs, run 'nix log /nix/store/s8xcb7jh5jsvkwmmllrj1v3rqfxdgx86-ex_cldr_currencies-2.16.1.drv'.
error: 1 dependencies of derivation '/nix/store/c034drbbvivpy1jjrajjakaxi9r4zbjl-locale-repro-0.1.0.drv' failed to build
```

**Comment by camelpunch** [comment]
And here's [the `workaround](https://github.com/camelpunch/locale_repro/compare/main..fix).

It builds and works:

```
$ nix build -L github:camelpunch/locale_repro/fix
$ echo $?
0
```

**Comment by kipcole9** [comment]
I struggle with Nix (which means that while I understand the principles, I am totally intimidated by it and the whole ecosystem).

I have pushed [this commit](https://github.com/elixir-cldr/cldr/commit/00d4559ee26841e79271fb6413cd2ca781c99071) that makes `Cldr.Config.cldr_data_dir/0` to be a runtime value, not a compile time value.  

I think that has a fair chance of resolving some, if not all, of the fundamental issue. I'm just running tests now and then I'll publish a new release for you to try.

**Comment by kipcole9** [comment]
I've published [ex_cldr version 2.38.1](https://hex.pm/packages/ex_cldr/2.38.1) with the following changelog entry:

### Bug Fixes

* Fix warnings on Elixir 1.17. This primarily relates to charlists constants now required to use `sigil_c` to avoid warnings. As a result, tests will only work on Elixir 1.16 and later even though support for the library is for Elixir 1.11 and later.

* Make `Cldr.Config.cldr_data_dir/0` a runtime result, not a compile time result.

* Sort currency data in `Cldr.Config.territories/0` so ensure deterministic order. Closes #227.

Do you think you could give that a try and see if it resolves some, if not all, of the issues you're seeing with Nix.  Except the lack of `config/prod.exs` on some libs.

**Comment by camelpunch** [comment]
Yeah Nix is a nightmare! It solves a lot of problems though, so I’m trying to make it better friends with Elixir. 

Really appreciate your efforts here. Will give them a spin.

**Comment by camelpunch** [comment]
Success! This change does mean we can remove our workarounds. Thanks so much!

Closing this PR. I'll continue to annoy you with blank `prod.exs` PRs for the other libs :)

**Comment by kipcole9** [comment]
Thanks for confirming, and no problem adding `config/prod.exs` on all the libs as you need them (or as a main release comes up). No annoyance at all.
